version: '3.9'

services:
  mysql:
    image: mysql:8.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?set}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-singre}
      MYSQL_USER: ${MYSQL_USER:-singre}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?set}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  backend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_ORG:-your-org}/singre-backend:${BACKEND_TAG:-latest}
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'echo > /dev/tcp/127.0.0.1/9000' "]
      interval: 10s
      timeout: 5s
      retries: 10
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY:?set}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-singre}
      DB_USERNAME: ${MYSQL_USER:-singre}
      DB_PASSWORD: ${MYSQL_PASSWORD:?set}
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/html:ro
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost || exit 1"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  frontend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_ORG:-your-org}/singre-frontend:${FRONTEND_TAG:-latest}
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost || exit 1"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

volumes:
  mysql_data:
