version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?set}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-singre}
      MYSQL_USER: ${MYSQL_USER:-singre}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?set}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_ORG:-your-org}/singre-backend:${BACKEND_TAG:-latest}
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY:?set}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-singre}
      DB_USERNAME: ${MYSQL_USER:-singre}
      DB_PASSWORD: ${MYSQL_PASSWORD:?set}
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - backend
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/html:ro
    ports:
      - "80:80"
    restart: unless-stopped

  frontend:
    image: ${REGISTRY:-ghcr.io}/${IMAGE_ORG:-your-org}/singre-frontend:${FRONTEND_TAG:-latest}
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  mysql_data:
