services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-singre}
      MYSQL_USER: ${MYSQL_USER:-singre}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-singre}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025" # SMTP
      - "${MAILPIT_UI_PORT:-8025}:8025" # Web UI

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      mailpit:
        condition: service_started
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:dummykeyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${MYSQL_DATABASE:-singre}
      DB_USERNAME: ${MYSQL_USER:-singre}
      DB_PASSWORD: ${MYSQL_PASSWORD:-singre}
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: noreply@example.com
      MAIL_FROM_NAME: "SINGRE"
    volumes:
      - ./backend:/var/www/html
      - ./docker/backend/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./docker/backend/fpm-overrides.conf:/usr/local/etc/php-fpm.d/zz-overrides.conf:ro
    ports:
      - "${PHPFPM_HOST_PORT:-9000}:9000" # php-fpm
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'echo > /dev/tcp/127.0.0.1/9000' "]
      interval: 5s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_HOST_PORT:-8080}:80"
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1; pidof nginx || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
      target: ${FRONTEND_DOCKER_TARGET:-final-static}
    ports:
      - "${FRONTEND_HOST_PORT:-5173}:80"
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1; pidof nginx || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  mysql_data:
