name: Backend CI

on:
  push:
    branches: [ master, main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'backend/**'

jobs:
  php-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, pdo_mysql, tokenizer
          coverage: none

      - name: Validate composer.json & composer.lock
        run: composer validate --no-interaction

      - name: Install dependencies
        run: composer install --no-interaction --no-scripts --prefer-dist

      - name: Syntax check
        run: |
          find app -type f -name "*.php" -print0 | xargs -0 -n1 php -l

  docker-image:
    needs: php-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend/Dockerfile
          push: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/singre-backend:latest
