apiVersion: 1
contactPoints:
  - orgId: 1
    name: slack
    receivers:
      - uid: slack-default
        type: slack
        settings:
          url: ${GRAFANA_SLACK_WEBHOOK_URL}
          recipient: "#alerts"
          username: "Grafana"
          icon_emoji: ":rotating_light:"
