name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ${{ vars.REGISTRY || 'ghcr.io' }}
      IMAGE_ORG: ${{ vars.IMAGE_ORG || github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/singre-backend
            ${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}/singre-frontend

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push frontend (final-built)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend/Dockerfile
          target: final-built
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Show compose.prod with resolved images
        run: |
          sed -e "s|ghcr.io/your-org|${{ env.REGISTRY }}/${{ env.IMAGE_ORG }}|g" docker-compose.prod.yml
