name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/backend/Dockerfile
          push: false
          tags: backend:ci

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/frontend/Dockerfile
          target: final-static
          push: false
          tags: frontend:ci

      - name: Compose up (dev)
        run: |
          cp -n .env.example .env || true
          docker compose up -d --build

      - name: Healthcheck
        run: |
          curl -fsS http://localhost:8080 || (docker compose logs nginx backend && exit 1)
          curl -fsS http://localhost:5173 || (docker compose logs frontend && exit 1)

      - name: Compose down
        if: always()
        run: docker compose down -v
