name: OpenAPI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/openapi.yml'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare application key
        run: |
          cp -n .env.example .env || true
          php artisan key:generate --force

      - name: Generate OpenAPI JSON
        run: php artisan l5-swagger:generate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-json
          path: backend/storage/api-docs/
