name: Security

on:
  push:
    branches: ["**"]
  pull_request:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS scan (repo)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

  trivy-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy config scan (IaC)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          format: table
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

  trivy-image-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: |
          docker build -t backend:test -f docker/backend/Dockerfile .
      - name: Trivy image scan (backend)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: backend:test
          format: table
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
